#!/bin/sh
###########################
# ----------------------- #
# Xiongnu - Service Start #
# ----------------------- #
###########################
# rcS - Service Start
####################################
# Copyright (C) 2018 Alex Barris - All Rights Reserved
# Awlsome Public License v1.0
# v1.2.2a

for i in /etc/init.d/S??* ;do
	[ ! -f "$i" ] && continue
	case "$i" in
	*.sh)
		# Shell Source Script
		(
		trap - INT QUIT TSTP
		set start
		. $i
		)
		;;
	*)
		# Fork Subprocess
		$i start
		;;
	esac
done
