#!/bin/sh
#############################
# ------------------------- #
# Xiongnu - Network Service #
# ------------------------- #
#############################
# Network Service
####################################
# Copyright (C) 2018 Alex Barris - All Rights Reserved
# Awlsome Public License v1.0
# v1.2.2a

. /lib/libstar/common.lib

case "$1" in
	start)
		common_print "Starting Network Devices...." -s ....
		for DEVICE in /sys/class/net/* ; do
			ip link set ${DEVICE##*/} up
			common_print "Started Network Device ${DEVICE##*/}" -s DONE
			[ ${DEVICE##*/} = wlan0 ] && wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf
			[ ${DEVICE##*/} != lo ] && [ ${DEVICE##*/} != sit0 ] && udhcpc -b -i ${DEVICE##*/} -s /etc/init.d/rc.udhcp
		done
		;;
	stop)
		common_print "Stopping Network Devices...." -s ....
		for DEVICE in /sys/class/net/* ; do
			ip link set ${DEVICE##*/} down
			common_print "Stopped Network Device ${DEVICE##*/}" -s DONE
		done
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		common_print "Usage: $0 {start|stop|restart}" -c Red
esac
exit $?
