#!/bin/sh

#########################
# StarLinux Init Script #
#########################
# Made by AwlsomeAlex
# Adapted for StarLinux from Gentoo

case "$1" in
	start)
		echo -e "\e[1;94m(****) \e[0mStarting Network Devices..."
		for DEVICE in /sys/class/net/* ; do
			ip link set ${DEVICE##*/} up
			echo -e "\e[1;32m(PASS) \e[0mStarted Network Device ${DEVICE##*/}"
			[ ${DEVICE##*/} = wlan0 ] && wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf
			[ ${DEVICE##*/} != lo ] && [ ${DEVICE##*/} != sit0 ] && udhcpc -b -i ${DEVICE##*/} -s /etc/init.d/rc.udhcp
		done
		# /sbin/ifup -a
		;;
	stop)
		echo -e "\e[1;94m(****) \e[0mStopping Network Devices..."
		for DEVICE in /sys/class/net/* ; do
			ip link set ${DEVICE##*/} down
			echo -e "\e[1;32m(PASS) \e[0mStopped Network Device ${DEVICE##*/}"
		done
		# /sbin/ifdown -a
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
esac

exit $?
